### ISSUE TITLE
Is not working for me

### ISSUE THREAD

**Issue by plexmax** [debauchery1st/super-duper-barnacle#1]
I did exaclty the instructions, cant reach the localhost:5000/stacitc/xml

what i missed?
I have ports open, xteve working and run.sh does not give me an error

**Comment by debauchery1st** [comment]
check that the IP of the hdhomerun tuner is correct and that you can reach it through your web browser.

if the tuner IP is correct, try a different port. another program may have reserved it.
(edit run.sh for your working environment)
